#!/usr/bin/env bash
# Check if battery is charging
read -r status0 < /sys/class/power_supply/BAT0/status
read -r status1 < /sys/class/power_supply/BAT1/status

if [[ "$status0" == "Charging" || "$status1" == "Charging" ]]
then
	# Exit if it is
	echo "Battery is charging $status0 $status1"
	exit 0
fi

# Calculate total capacity and send notification
read -r bat0 < /sys/class/power_supply/BAT0/capacity
read -r bat1 < /sys/class/power_supply/BAT1/capacity
total_capacity=$((((bat0 + bat1)) / 2))


if (( total_capacity < 10 ))
then
	notify-send "Battery Critical" "Current capacity is at $total_capacity%" -u critical
elif (( total_capacity < 20 ))
then
	notify-send "Battery Low" "Current capacity is at $total_capacity%" -u normal
fi
echo $total_capacity
